name: "Wait"
description: "Wait for a specified number of milliseconds"
inputs:
  ms:
    example: "1000"
    description: "Number of milliseconds to wait"
    required: true
    default: "1000"
outputs:
  time:
    description: "The current time after waiting"
runs:
  using: "node12"
  main: "dist/index.js"
