name: "Update Contributors"
description: "Updates the contributors.md file"
inputs:
  ms:
    example: "1000"
    description: "Number of milliseconds to wait"
    required: true
    default: "1000"
  repo:
    example: "risadams/risadams.com"
    description: "The repository to watch"
    required: true
    default: "risadams/risadams.com"
  exclude_bots:
    example: "true"
    description: "Exclude bots from the contributors list"
    required: true
    default: "true"
  output:
    example: "./contributors.md"
    description: "The output file"
    required: true
    default: "./contributors.md"
outputs:
  time:
    description: "The current time after waiting"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.exclude_bots }}
    - ${{ inputs.output }}
    - ${{ inputs.ms }}
