name: "Update Contributors"
description: "Updates the contributors.md file"
inputs:
  repo:
    example: "risadams/risadams.com"
    description: "The repository to watch"
    required: true
    default: "risadams/risadams.com"
  exclude_bots:
    example: "true"
    description: "Exclude bots from the contributors list"
    required: true
    default: "true"
outputs:
  contribs:
    description: "The contents of the contributors file"
runs:
  using: "node14"
  main: "src/index.js"
