name: Update Contributors
on: workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: risadams/contributors-update@v3
        with:
          repo: risadams/risadams.com
          output: CONTRIBUTORS.md
          exclude_bots: true
